# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-17 22:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('consumer', '0003_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_account_admin', models.BooleanField(default=False)),
                ('license_expires', models.DateTimeField()),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', models.CharField(max_length=9)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address1', models.CharField(max_length=128)),
                ('address2', models.CharField(blank=True, max_length=128)),
                ('country', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=64)),
                ('zip_code', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerDatapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=128)),
                ('remark', models.CharField(max_length=512)),
                ('created_time', models.DateTimeField()),
                ('last_modified', models.DateTimeField()),
                ('last_modified_by', models.CharField(max_length=30)),
                ('consumer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer.Consumer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapoint', models.CharField(max_length=256)),
                ('answer_type', models.CharField(max_length=20)),
                ('options', models.CharField(max_length=2048)),
            ],
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='consumerdatapoint',
            name='datapoint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer.Datapoint'),
        ),
        migrations.AlterUniqueTogether(
            name='consumerdatapoint',
            unique_together=set([('consumer_id', 'datapoint_id')]),
        ),
    ]
