# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 03:35
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0005_auto_20170824_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='state',
            field=localflavor.us.models.USStateField(default='state_unselected', max_length=2),
        ),
        migrations.AlterField(
            model_name='consumer',
            name='dob',
            field=models.DateField(),
        ),
    ]
