# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0007_auto_20171018_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
