# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-19 00:35
from __future__ import unicode_literals

from django.db import migrations
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('consumer', '0008_auto_20171018_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='state',
            field=localflavor.us.models.USStateField(default='state', max_length=2),
        ),
    ]
