# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-26 05:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_localflavor_us.models
import fernet_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=64)),
                ('is_active', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(verbose_name='date joined')),
                ('license_expires', models.DateTimeField(verbose_name='license expires')),
            ],
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssn', fernet_fields.fields.EncryptedTextField()),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('date_of_birth', models.DateTimeField(verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('address1', models.CharField(max_length=128, verbose_name='address1')),
                ('address2', models.CharField(blank=True, max_length=128, verbose_name='address2')),
                ('city', models.CharField(max_length=64, verbose_name='city')),
                ('state', django_localflavor_us.models.USStateField(choices=[(b'AL', b'Alabama'), (b'AK', b'Alaska'), (b'AS', b'American Samoa'), (b'AZ', b'Arizona'), (b'AR', b'Arkansas'), (b'AA', b'Armed Forces Americas'), (b'AE', b'Armed Forces Europe'), (b'AP', b'Armed Forces Pacific'), (b'CA', b'California'), (b'CO', b'Colorado'), (b'CT', b'Connecticut'), (b'DE', b'Delaware'), (b'DC', b'District of Columbia'), (b'FL', b'Florida'), (b'GA', b'Georgia'), (b'GU', b'Guam'), (b'HI', b'Hawaii'), (b'ID', b'Idaho'), (b'IL', b'Illinois'), (b'IN', b'Indiana'), (b'IA', b'Iowa'), (b'KS', b'Kansas'), (b'KY', b'Kentucky'), (b'LA', b'Louisiana'), (b'ME', b'Maine'), (b'MD', b'Maryland'), (b'MA', b'Massachusetts'), (b'MI', b'Michigan'), (b'MN', b'Minnesota'), (b'MS', b'Mississippi'), (b'MO', b'Missouri'), (b'MT', b'Montana'), (b'NE', b'Nebraska'), (b'NV', b'Nevada'), (b'NH', b'New Hampshire'), (b'NJ', b'New Jersey'), (b'NM', b'New Mexico'), (b'NY', b'New York'), (b'NC', b'North Carolina'), (b'ND', b'North Dakota'), (b'MP', b'Northern Mariana Islands'), (b'OH', b'Ohio'), (b'OK', b'Oklahoma'), (b'OR', b'Oregon'), (b'PA', b'Pennsylvania'), (b'PR', b'Puerto Rico'), (b'RI', b'Rhode Island'), (b'SC', b'South Carolina'), (b'SD', b'South Dakota'), (b'TN', b'Tennessee'), (b'TX', b'Texas'), (b'UT', b'Utah'), (b'VT', b'Vermont'), (b'VI', b'Virgin Islands'), (b'VA', b'Virginia'), (b'WA', b'Washington'), (b'WV', b'West Virginia'), (b'WI', b'Wisconsin'), (b'WY', b'Wyoming')], max_length=2, verbose_name='state')),
                ('zip_code', models.CharField(max_length=5, verbose_name='zip code')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerDataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=512)),
                ('remark', models.CharField(max_length=512)),
                ('created_date_time', models.DateTimeField(verbose_name='created date time')),
                ('last_modified_date_time', models.DateTimeField(verbose_name='last modified date time')),
                ('consumer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_datapoint.Consumer')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DataPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapoint', models.CharField(max_length=1028)),
                ('answer_type', models.CharField(choices=[('T', 'Text'), ('R', 'Radio'), ('D', 'DropDown'), ('C', 'Checkbox')], max_length=1)),
                ('options', models.CharField(max_length=1028)),
            ],
        ),
        migrations.CreateModel(
            name='DataPointDPGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datapoint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_datapoint.DataPoint')),
            ],
        ),
        migrations.CreateModel(
            name='DPGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
                ('datapoint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_datapoint.DataPoint')),
            ],
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_is_account_admin', models.BooleanField(default=False)),
                ('account_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_datapoint.Account')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='datapointdpgroup',
            name='dp_group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_datapoint.DPGroup'),
        ),
        migrations.AddField(
            model_name='consumerdatapoint',
            name='datapoint_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consumer_datapoint.DataPoint'),
        ),
        migrations.AddField(
            model_name='consumerdatapoint',
            name='last_modified_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='last_modified_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
